import Vue from "vue";
import Vuex from "vuex";
import getters from "./getters";
import actions from "./actions";
import mutations from "./mutations";

Vue.use(Vuex);

const state = {
  isUser: false,
  email: "",
  summonerName : "",
  summonerWinLose: {},
  summoner: {},
  champ: [
    { id: "Aatrox", key: "266", name: "아트록스" },
    { id: "Ahri", key: "103", name: "아리" },
    { id: "Akali", key: "84", name: "아칼리" },
    { id: "Alistar", key: "12", name: "알리스타" },
    { id: "Amumu", key: "32", name: "아무무" },
    { id: "Anivia", key: "34", name: "애니비아" },
    { id: "Annie", key: "1", name: "애니" },
    { id: "Aphelios", key: "523", name: "아펠리오스" },
    { id: "Ashe", key: "22", name: "애쉬" },
    { id: "AurelionSol", key: "136", name: "아우렐리온 솔" },
    { id: "Azir", key: "268", name: "아지르" },
    { id: "Bard", key: "432", name: "바드" },
    { id: "Blitzcrank", key: "53", name: "블리츠크랭크" },
    { id: "Brand", key: "63", name: "브랜드" },
    { id: "Braum", key: "201", name: "브라움" },
    { id: "Caitlyn", key: "51", name: "케이틀린" },
    { id: "Camille", key: "164", name: "카밀" },
    { id: "Cassiopeia", key: "69", name: "카시오페아" },
    { id: "Chogath", key: "31", name: "초가스" },
    { id: "Corki", key: "42", name: "코르키" },
    { id: "Darius", key: "122", name: "다리우스" },
    { id: "Diana", key: "131", name: "다이애나" },
    { id: "Draven", key: "119", name: "드레이븐" },
    { id: "DrMundo", key: "36", name: "문도 박사" },
    { id: "Ekko", key: "245", name: "에코" },
    { id: "Elise", key: "60", name: "엘리스" },
    { id: "Evelynn", key: "28", name: "이블린" },
    { id: "Ezreal", key: "81", name: "이즈리얼" },
    { id: "Fiddlesticks", key: "9", name: "피들스틱" },
    { id: "Fiora", key: "114", name: "피오라" },
    { id: "Fizz", key: "105", name: "피즈" },
    { id: "Galio", key: "3", name: "갈리오" },
    { id: "Gangplank", key: "41", name: "갱플랭크" },
    { id: "Garen", key: "86", name: "가렌" },
    { id: "Gnar", key: "150", name: "나르" },
    { id: "Gragas", key: "79", name: "그라가스" },
    { id: "Graves", key: "104", name: "그레이브즈" },
    { id: "Hecarim", key: "120", name: "헤카림" },
    { id: "Heimerdinger", key: "74", name: "하이머딩거" },
    { id: "Illaoi", key: "420", name: "일라오이" },
    { id: "Irelia", key: "39", name: "이렐리아" },
    { id: "Ivern", key: "427", name: "아이번" },
    { id: "Janna", key: "40", name: "잔나" },
    { id: "JarvanIV", key: "59", name: "자르반 4세" },
    { id: "Jax", key: "24", name: "잭스" },
    { id: "Jayce", key: "126", name: "제이스" },
    { id: "Jhin", key: "202", name: "진" },
    { id: "Jinx", key: "222", name: "징크스" },
    { id: "Kaisa", key: "145", name: "카이사" },
    { id: "Kalista", key: "429", name: "칼리스타" },
    { id: "Karma", key: "43", name: "카르마" },
    { id: "Karthus", key: "30", name: "카서스" },
    { id: "Kassadin", key: "38", name: "카사딘" },
    { id: "Katarina", key: "55", name: "카타리나" },
    { id: "Kayle", key: "10", name: "케일" },
    { id: "Kayn", key: "141", name: "케인" },
    { id: "Kennen", key: "85", name: "케넨" },
    { id: "Khazix", key: "121", name: "카직스" },
    { id: "Kindred", key: "203", name: "킨드레드" },
    { id: "Kled", key: "240", name: "클레드" },
    { id: "KogMaw", key: "96", name: "코그모" },
    { id: "Leblanc", key: "7", name: "르블랑" },
    { id: "LeeSin", key: "64", name: "리 신" },
    { id: "Leona", key: "89", name: "레오나" },
    { id: "Lillia", key: "876", name: "릴리아" },
    { id: "Lissandra", key: "127", name: "리산드라" },
    { id: "Lucian", key: "236", name: "루시안" },
    { id: "Lulu", key: "117", name: "룰루" },
    { id: "Lux", key: "99", name: "럭스" },
    { id: "Malphite", key: "54", name: "말파이트" },
    { id: "Malzahar", key: "90", name: "말자하" },
    { id: "Maokai", key: "57", name: "마오카이" },
    { id: "MasterYi", key: "11", name: "마스터 이" },
    { id: "MissFortune", key: "21", name: "미스 포츈" },
    { id: "MonkeyKing", key: "62", name: "오공" },
    { id: "Mordekaiser", key: "82", name: "모데카이저" },
    { id: "Morgana", key: "25", name: "모르가나" },
    { id: "Nami", key: "267", name: "나미" },
    { id: "Nasus", key: "75", name: "나서스" },
    { id: "Nautilus", key: "111", name: "노틸러스" },
    { id: "Neeko", key: "518", name: "니코" },
    { id: "Nidalee", key: "76", name: "니달리" },
    { id: "Nocturne", key: "56", name: "녹턴" },
    { id: "Nunu", key: "20", name: "누누와 윌럼프" },
    { id: "Olaf", key: "2", name: "올라프" },
    { id: "Orianna", key: "61", name: "오리아나" },
    { id: "Ornn", key: "516", name: "오른" },
    { id: "Pantheon", key: "80", name: "판테온" },
    { id: "Poppy", key: "78", name: "뽀삐" },
    { id: "Pyke", key: "555", name: "파이크" },
    { id: "Qiyana", key: "246", name: "키아나" },
    { id: "Quinn", key: "133", name: "퀸" },
    { id: "Rakan", key: "497", name: "라칸" },
    { id: "Rammus", key: "33", name: "람머스" },
    { id: "RekSai", key: "421", name: "렉사이" },
    { id: "Renekton", key: "58", name: "레넥톤" },
    { id: "Rengar", key: "107", name: "렝가" },
    { id: "Riven", key: "92", name: "리븐" },
    { id: "Rumble", key: "68", name: "럼블" },
    { id: "Ryze", key: "13", name: "라이즈" },
    { id: "Samira", key: "360", name: "사미라" },
    { id: "Sejuani", key: "113", name: "세주아니" },
    { id: "Senna", key: "235", name: "세나" },
    { id: "Sett", key: "875", name: "세트" },
    { id: "Shaco", key: "35", name: "샤코" },
    { id: "Shen", key: "98", name: "쉔" },
    { id: "Shyvana", key: "102", name: "쉬바나" },
    { id: "Singed", key: "27", name: "신지드" },
    { id: "Sion", key: "14", name: "사이온" },
    { id: "Sivir", key: "15", name: "시비르" },
    { id: "Skarner", key: "72", name: "스카너" },
    { id: "Sona", key: "37", name: "소나" },
    { id: "Soraka", key: "16", name: "소라카" },
    { id: "Swain", key: "50", name: "스웨인" },
    { id: "Sylas", key: "517", name: "사일러스" },
    { id: "Syndra", key: "134", name: "신드라" },
    { id: "TahmKench", key: "223", name: "탐 켄치" },
    { id: "Taliyah", key: "163", name: "탈리야" },
    { id: "Talon", key: "91", name: "탈론" },
    { id: "Taric", key: "44", name: "타릭" },
    { id: "Teemo", key: "17", name: "티모" },
    { id: "Thresh", key: "412", name: "쓰레쉬" },
    { id: "Tristana", key: "18", name: "트리스타나" },
    { id: "Trundle", key: "48", name: "트런들" },
    { id: "Tryndamere", key: "23", name: "트린다미어" },
    { id: "TwistedFate", key: "4", name: "트위스티드 페이트" },
    { id: "Twitch", key: "29", name: "트위치" },
    { id: "Udyr", key: "77", name: "우디르" },
    { id: "Urgot", key: "6", name: "우르곳" },
    { id: "Varus", key: "110", name: "바루스" },
    { id: "Vayne", key: "67", name: "베인" },
    { id: "Veigar", key: "45", name: "베이가" },
    { id: "Velkoz", key: "161", name: "벨코즈" },
    { id: "Vi", key: "254", name: "바이" },
    { id: "Viktor", key: "112", name: "빅토르" },
    { id: "Vladimir", key: "8", name: "블라디미르" },
    { id: "Volibear", key: "106", name: "볼리베어" },
    { id: "Warwick", key: "19", name: "워윅" },
    { id: "Xayah", key: "498", name: "자야" },
    { id: "Xerath", key: "101", name: "제라스" },
    { id: "XinZhao", key: "5", name: "신 짜오" },
    { id: "Yasuo", key: "157", name: "야스오" },
    { id: "Yone", key: "777", name: "요네" },
    { id: "Yorick", key: "83", name: "요릭" },
    { id: "Yuumi", key: "350", name: "유미" },
    { id: "Zac", key: "154", name: "자크" },
    { id: "Zed", key: "238", name: "제드" },
    { id: "Ziggs", key: "115", name: "직스" },
    { id: "Zilean", key: "26", name: "질리언" },
    { id: "Zoe", key: "142", name: "조이" },
    { id: "Zyra", key: "143", name: "자이라" },
  ],
};

export default new Vuex.Store({
  state,
  mutations,
  getters,
  actions,
});
