import Vue from "vue";
import Vuex from "vuex";
import getters from "./getters";
import actions from "./actions";
import mutations from "./mutations";

Vue.use(Vuex);

const state = {
  isUser: false,
  email: "",
  summonerName: "",
  summonerWinLose: {},
  summoner: {},
  mbti: {
        "ISTJ" : {
                  "nick" : ["전략플래너", "확고한 의지로~!"], 
                  "detail" : "자신의 계획에 따라 게임을 플레이합니다. 팀원들의 조언 따위 보다는 자신의 계획님이 더 소중합니다.", 
                  "good" : "ISFJ", 
                  "bad" : "ENFP"
                  },
        "ISFJ" : {
                  "nick" : ["챗봇", "댕청미 매력"], 
                  "detail" : "팀원의 질문에 가장 빨리 반응하며 팀원들이 먹은 물약 갯수까지 기억하려 합니다. 칭찬은 바론보다 더 좋은 영약!!", 
                  "good" : "ENTJ", 
                  "bad" : "ESFJ"
                  },
        "INFJ" : {
                  "nick" : ["정신산만", "표정만은 페이커"], 
                  "detail" : "언제나 포커페이스를 유지하며 침착한 플레이를 보이는 것 같지만 다른 생각하신건 아니신가요? 과거의 펜타킬보다는 지금의 1킬이 중요하죠~", 
                  "good" : "INFJ", 
                  "bad" : "ISTJ"
                  }, 
        "INTJ" : {
                  "nick" : ["골목대장", "한타 ㄱㄱ"], 
                  "detail" : "한타 ㄱㄱ를 외치는 그대는 골목식당 아닌 골목대장! 풋ㅋ.... 멘탈만 안 터지면 팀을 잘 이끌어 주죠", 
                  "good" : "INTP", 
                  "bad" : "ESFJ"
                  }, 
        "ISTP" : {
                  "nick" : ["노력하는 열정맨", "또 제드야?"], 
                  "detail" : "장인정신으로 라인이나 챔프마다의 고유 메타를 가지고 있습니다. 신규 챔프가 나오면 나만의 메타로 만들기 위해 노오오오오력!", 
                  "good" : "ESTP", 
                  "bad" : "INTP"
                  }, 
        "ISFP" : {
                  "nick" : ["신챔나옴? 크", "오늘은 뭐하지?"], 
                  "detail" : "하나의 챔프를 파기보다는 모든 챔프를 실험해보고 이전 플레이한 챔프를 고려하여 겹치지 않게 챔피언을 선택하여 플레이합니다.", 
                  "good" : "ISFP", 
                  "bad" : "ENTJ"
                  }, 
        "INFP" : { 
                  "nick" : ["멘탈바사삭"], 
                  "detail" : "채팅을 조심해주세요. 여려요. 착해요. 담아둬요. 싸우지 않아요. 착해요. 본인의 역할을 충실히 하려고 노력해요.", 
                  "good" : "ENFP", 
                  "bad" : "ESTJ"
                  }, 
        "INTP" : { 
                  "nick" : ["남탓장인", "콜롬버스메타"], 
                  "detail" : "게임이 잘 풀리지 않을 때 건들면 물어요. 항상 새로운 전략을 연구하며 자신만의 캐릭터를 창조하죠~", 
                  "good" : "ENTJ", 
                  "bad" : "ESFJ",
                  }, 
        "ESTP" : { 
                  "nick" : ["빠른 포기", "멀티플레이어"], 
                  "detail" : "혹시 게임 중 아프리카TV나 인터넷 창을 띄워놓으셨나요? 팀의 승패보다는 나의 재미를 찾는 플레이를 즐기시는군요?", 
                  "good" : "ISTJ", 
                  "bad" : "INFP"
                  }, 
        "ESFP" : { 
                  "nick" : ["화려한 조명이", "날 감싸네"], 
                  "detail" : "팀의 승리보다는 펜타킬이 더 중요합니다. 옆에 잘 챙겨주는 사람과의 듀오는 나의 실력을 눈에 띄게 달라지게 합니다.", 
                  "good" : "ESFP", 
                  "bad" : "INTJ"
                  }, 
        "ENFP" : { 
                  "nick" : ["딴짓대마왕", "언제 시작함?"], 
                  "detail" : "게임 로딩시간에 딴짓으로 미니언 놓치거나 리쉬를 늦은 적이 있다?없다?. 늦었다고 생각할 때는 정말 늦은거다~!", 
                  "good" : "INTJ", 
                  "bad" : "ISTJ"
                  }, 
        "ENTP" : { 
                  "nick" : ["첫챗은 내차지", "채팅창 주인"], 
                  "detail" : "한 라인을 파기보다는 모든 챔프와 모든 라인을 돌며 실력을 인정받고 싶어~ 남들보다 채팅창 기능을 활용하기 위해서는 빠른 손이 필수~!", 
                  "good" : "ENTP", 
                  "bad" : "ENTJ"
                  }, 
        "ESTJ" : { 
                  "nick" : ["난 강하지만", "부셔지기 쉽다."], 
                  "detail" : "플레이에 완벽을 추구하기에 팀에 큰 도움이 됩니다. 하지만 멘탈이 깨지는 순간 탈주보다 더한 악재가........", 
                  "good" : "ENTJ", 
                  "bad" : "INFP"
                  }, 
        "ESFJ" : { 
                  "nick" : ["꼬꼬마 질문봇", "관심 좀..."], 
                  "detail" : "플레이에 궁금한게 생기면 팀원들에게 묻고 잘 소통합니다. 따뜻한 한마디 우리 꼬꼬마 마음을 헤치지 마세요.", 
                  "good" : "ISTP", 
                  "bad" : "INFJ"
                  }, 
        "ENFJ" : { 
                  "nick" : ["탑신봉자", "영혼의 맞다이"], 
                  "detail" : "팀을 위해서 나의 라인을 지켜야 합니다. 나의 라인 상대는 내가 이기고 합류할게. 기억해죠!!!!!", 
                  "good" : "ISTJ", 
                  "bad" : "ESFP"
                  }, 
        "ENTJ" : { 
                  "nick" : ["나를 욕하시오", "식구 아닌교?"], 
                  "detail" : "팀이 되는 순간 한없이 나의 편으로 생각하고 챙겨줍니다. 따뜻하게 챙겨주는 부모 같은 사람에겐 욕하지 맙시다.", 
                  "good" : "ENTP", 
                  "bad" : "ISFP"
                  },
        },
  gameitems: {
    "1400": "마법 부여: 용사",
    "1401": "마법 부여: 잿불거인",
    "1402": "마법 부여: 룬의 메아리",
    "1412": "마법 부여: 용사",
    "1413": "마법 부여: 잿불거인",
    "1414": "마법 부여: 룬의 메아리",
    "1416": "마법 부여: 피갈퀴손",
    "1419": "마법 부여: 피갈퀴손",
    "2065": "슈렐리아의 몽상",
    "3003": "대천사의 지팡이",
    "3004": "마나무네",
    "3006": "광전사의 군화",
    "3009": "신속의 장화",
    "3020": "마법사의 신발",
    "3022": "얼어붙은망치",
    "3026": "수호 천사",
    "3027": "영겁의 지팡이",
    "3030": "마법공학 GLP-800",
    "3033": "필멸자의 운명",
    "3036": "도미닉 경의 인사",
    "3041": "메자이의 영혼약탈자",
    "3046": "유령 무희",
    "3047": "닌자의 신발",
    "3050": "지크의 융합",
    "3053": "스테락의 도전",
    "3065": "정령의 형상",
    "3072": "피바라기",
    "3074": "굶주린 히드라",
    "3075": "가시 갑옷",
    "3083": "워모그의 갑옷",
    "3085": "루난의 허리케인",
    "3087": "스태틱의 단검",
    "3091": "마법사의 최후",
    "3094": "고속 연사포",
    "3095": "폭풍갈퀴",
    "3100": "리치베인",
    "3102": "밴시의 장막",
    "3109": "기사의 맹세",
    "3110": "얼어붙은 심장",
    "3111": "헤르메스의 발걸음",
    "3115": "내셔의 이빨",
    "3116": "라일라이의 수정홀",
    "3117": "기동력의 장화",
    "3124": "구인수의 격노검",
    "3135": "공허의 지팡이",
    "3139": "헤르메스의 시미터",
    "3143": "란두인의 예언",
    "3146": "마법공학 총검",
    "3147": "드락사르의 황혼검",
    "3151": "리안드리의 고통",
    "3152": "마법공학 초기형 벨트-01",
    "3156": "맬모셔스의 아귀",
    "3158": "명석함의 아이오니아 장화",
    "3165": "모렐로노미콘",
    "3174": "아테나의 부정한 성배",
    "3179": "그림자 검",
    "3181": "핏빛 칼날",
    "3193": "가고일 돌갑옷",
    "3194": "적응형 투구",
    "3222": "미카엘의 도가니",
    "3031": "무한의 대검",
    "3068": "태양불꽃 망토",
    "3089": "라바돈의 죽음모자",
    "3001": "심연의 가면",
    "3071": "칠흑의 양날 도끼",
    "3107": "구원",
    "3190": "강철의 솔라리 펜던트",
    "3078": "삼위일체",
    "3157": "존야의 모래시계",
    "3025": "얼어붙은 건틀릿",
    "3142": "요우무의 유령검",
    "3153": "몰락한 왕의 검",
    "3285": "루덴의 메아리",
    "3504": "불타는 향로",
    "3508": "정수 약탈자",
    "3742": "망자의 갑옷",
    "3748": "거대한 히드라",
    "3800": "정당한 영광",
    "3812": "죽음의 무도",
    "3814": "밤의 끝자락",
    "3905": "쌍둥이 그림자",
    "3907": "주문매듭 구슬",
    "3198": "완성형 마공학 핵",
    "3853": "얼음 정수의 파편",
    "3857": "화이트록의 갑옷",
    "3860": "타곤 산의 방벽",
    "3864": "검은 안개 낫",
  },

  champ: [
    { id: "Aatrox", key: "266", name: "아트록스" },
    { id: "Ahri", key: "103", name: "아리" },
    { id: "Akali", key: "84", name: "아칼리" },
    { id: "Alistar", key: "12", name: "알리스타" },
    { id: "Amumu", key: "32", name: "아무무" },
    { id: "Anivia", key: "34", name: "애니비아" },
    { id: "Annie", key: "1", name: "애니" },
    { id: "Aphelios", key: "523", name: "아펠리오스" },
    { id: "Ashe", key: "22", name: "애쉬" },
    { id: "AurelionSol", key: "136", name: "아우렐리온 솔" },
    { id: "Azir", key: "268", name: "아지르" },
    { id: "Bard", key: "432", name: "바드" },
    { id: "Blitzcrank", key: "53", name: "블리츠크랭크" },
    { id: "Brand", key: "63", name: "브랜드" },
    { id: "Braum", key: "201", name: "브라움" },
    { id: "Caitlyn", key: "51", name: "케이틀린" },
    { id: "Camille", key: "164", name: "카밀" },
    { id: "Cassiopeia", key: "69", name: "카시오페아" },
    { id: "Chogath", key: "31", name: "초가스" },
    { id: "Corki", key: "42", name: "코르키" },
    { id: "Darius", key: "122", name: "다리우스" },
    { id: "Diana", key: "131", name: "다이애나" },
    { id: "Draven", key: "119", name: "드레이븐" },
    { id: "DrMundo", key: "36", name: "문도 박사" },
    { id: "Ekko", key: "245", name: "에코" },
    { id: "Elise", key: "60", name: "엘리스" },
    { id: "Evelynn", key: "28", name: "이블린" },
    { id: "Ezreal", key: "81", name: "이즈리얼" },
    { id: "Fiddlesticks", key: "9", name: "피들스틱" },
    { id: "Fiora", key: "114", name: "피오라" },
    { id: "Fizz", key: "105", name: "피즈" },
    { id: "Galio", key: "3", name: "갈리오" },
    { id: "Gangplank", key: "41", name: "갱플랭크" },
    { id: "Garen", key: "86", name: "가렌" },
    { id: "Gnar", key: "150", name: "나르" },
    { id: "Gragas", key: "79", name: "그라가스" },
    { id: "Graves", key: "104", name: "그레이브즈" },
    { id: "Hecarim", key: "120", name: "헤카림" },
    { id: "Heimerdinger", key: "74", name: "하이머딩거" },
    { id: "Illaoi", key: "420", name: "일라오이" },
    { id: "Irelia", key: "39", name: "이렐리아" },
    { id: "Ivern", key: "427", name: "아이번" },
    { id: "Janna", key: "40", name: "잔나" },
    { id: "JarvanIV", key: "59", name: "자르반 4세" },
    { id: "Jax", key: "24", name: "잭스" },
    { id: "Jayce", key: "126", name: "제이스" },
    { id: "Jhin", key: "202", name: "진" },
    { id: "Jinx", key: "222", name: "징크스" },
    { id: "Kaisa", key: "145", name: "카이사" },
    { id: "Kalista", key: "429", name: "칼리스타" },
    { id: "Karma", key: "43", name: "카르마" },
    { id: "Karthus", key: "30", name: "카서스" },
    { id: "Kassadin", key: "38", name: "카사딘" },
    { id: "Katarina", key: "55", name: "카타리나" },
    { id: "Kayle", key: "10", name: "케일" },
    { id: "Kayn", key: "141", name: "케인" },
    { id: "Kennen", key: "85", name: "케넨" },
    { id: "Khazix", key: "121", name: "카직스" },
    { id: "Kindred", key: "203", name: "킨드레드" },
    { id: "Kled", key: "240", name: "클레드" },
    { id: "KogMaw", key: "96", name: "코그모" },
    { id: "Leblanc", key: "7", name: "르블랑" },
    { id: "LeeSin", key: "64", name: "리 신" },
    { id: "Leona", key: "89", name: "레오나" },
    { id: "Lillia", key: "876", name: "릴리아" },
    { id: "Lissandra", key: "127", name: "리산드라" },
    { id: "Lucian", key: "236", name: "루시안" },
    { id: "Lulu", key: "117", name: "룰루" },
    { id: "Lux", key: "99", name: "럭스" },
    { id: "Malphite", key: "54", name: "말파이트" },
    { id: "Malzahar", key: "90", name: "말자하" },
    { id: "Maokai", key: "57", name: "마오카이" },
    { id: "MasterYi", key: "11", name: "마스터 이" },
    { id: "MissFortune", key: "21", name: "미스 포츈" },
    { id: "MonkeyKing", key: "62", name: "오공" },
    { id: "Mordekaiser", key: "82", name: "모데카이저" },
    { id: "Morgana", key: "25", name: "모르가나" },
    { id: "Nami", key: "267", name: "나미" },
    { id: "Nasus", key: "75", name: "나서스" },
    { id: "Nautilus", key: "111", name: "노틸러스" },
    { id: "Neeko", key: "518", name: "니코" },
    { id: "Nidalee", key: "76", name: "니달리" },
    { id: "Nocturne", key: "56", name: "녹턴" },
    { id: "Nunu", key: "20", name: "누누와 윌럼프" },
    { id: "Olaf", key: "2", name: "올라프" },
    { id: "Orianna", key: "61", name: "오리아나" },
    { id: "Ornn", key: "516", name: "오른" },
    { id: "Pantheon", key: "80", name: "판테온" },
    { id: "Poppy", key: "78", name: "뽀삐" },
    { id: "Pyke", key: "555", name: "파이크" },
    { id: "Qiyana", key: "246", name: "키아나" },
    { id: "Quinn", key: "133", name: "퀸" },
    { id: "Rakan", key: "497", name: "라칸" },
    { id: "Rammus", key: "33", name: "람머스" },
    { id: "RekSai", key: "421", name: "렉사이" },
    { id: "Renekton", key: "58", name: "레넥톤" },
    { id: "Rengar", key: "107", name: "렝가" },
    { id: "Riven", key: "92", name: "리븐" },
    { id: "Rumble", key: "68", name: "럼블" },
    { id: "Ryze", key: "13", name: "라이즈" },
    { id: "Samira", key: "360", name: "사미라" },
    { id: "Sejuani", key: "113", name: "세주아니" },
    { id: "Senna", key: "235", name: "세나" },
    { id: "Sett", key: "875", name: "세트" },
    { id: "Shaco", key: "35", name: "샤코" },
    { id: "Shen", key: "98", name: "쉔" },
    { id: "Shyvana", key: "102", name: "쉬바나" },
    { id: "Singed", key: "27", name: "신지드" },
    { id: "Sion", key: "14", name: "사이온" },
    { id: "Sivir", key: "15", name: "시비르" },
    { id: "Skarner", key: "72", name: "스카너" },
    { id: "Sona", key: "37", name: "소나" },
    { id: "Soraka", key: "16", name: "소라카" },
    { id: "Swain", key: "50", name: "스웨인" },
    { id: "Sylas", key: "517", name: "사일러스" },
    { id: "Syndra", key: "134", name: "신드라" },
    { id: "TahmKench", key: "223", name: "탐 켄치" },
    { id: "Taliyah", key: "163", name: "탈리야" },
    { id: "Talon", key: "91", name: "탈론" },
    { id: "Taric", key: "44", name: "타릭" },
    { id: "Teemo", key: "17", name: "티모" },
    { id: "Thresh", key: "412", name: "쓰레쉬" },
    { id: "Tristana", key: "18", name: "트리스타나" },
    { id: "Trundle", key: "48", name: "트런들" },
    { id: "Tryndamere", key: "23", name: "트린다미어" },
    { id: "TwistedFate", key: "4", name: "트위스티드 페이트" },
    { id: "Twitch", key: "29", name: "트위치" },
    { id: "Udyr", key: "77", name: "우디르" },
    { id: "Urgot", key: "6", name: "우르곳" },
    { id: "Varus", key: "110", name: "바루스" },
    { id: "Vayne", key: "67", name: "베인" },
    { id: "Veigar", key: "45", name: "베이가" },
    { id: "Velkoz", key: "161", name: "벨코즈" },
    { id: "Vi", key: "254", name: "바이" },
    { id: "Viktor", key: "112", name: "빅토르" },
    { id: "Vladimir", key: "8", name: "블라디미르" },
    { id: "Volibear", key: "106", name: "볼리베어" },
    { id: "Warwick", key: "19", name: "워윅" },
    { id: "Xayah", key: "498", name: "자야" },
    { id: "Xerath", key: "101", name: "제라스" },
    { id: "XinZhao", key: "5", name: "신 짜오" },
    { id: "Yasuo", key: "157", name: "야스오" },
    { id: "Yone", key: "777", name: "요네" },
    { id: "Yorick", key: "83", name: "요릭" },
    { id: "Yuumi", key: "350", name: "유미" },
    { id: "Zac", key: "154", name: "자크" },
    { id: "Zed", key: "238", name: "제드" },
    { id: "Ziggs", key: "115", name: "직스" },
    { id: "Zilean", key: "26", name: "질리언" },
    { id: "Zoe", key: "142", name: "조이" },
    { id: "Zyra", key: "143", name: "자이라" },
  ],
};

export default new Vuex.Store({
  state,
  mutations,
  getters,
  actions,
});
